name: RAPZ-TELE-GEN

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Deps
        run: pip install requests pycryptodome pyTelegramBotAPI urllib3

      - name: Start Bot Engine
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          # Jalanin bot selama 5.5 jam
          timeout 19800s python bot.py || echo "Session End"

      - name: Auto Sync to Repo
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "AW-Deployer"
          git add .
          git commit -m "Auto Sync Cloud Data" || echo "No changes"
          git push
